use ghost_kitchen_analysis;

/* 
--------------------------------------------------------------------------------
- Customer Analysis
--------------------------------------------------------------------------------

-- 1. Customer Order Activity
- First, find out how many orders each customers has placed?
*/

select customer_id, count(order_id) as total_orders
from orders
group by customer_id
order by total_orders desc;

/*
- 2. Customer Spending Analysis
- how much each customer has spent?
*/
select customer_id, sum(order_value) as total_spend
from orders
group by customer_id
order by total_spend desc;

/*
- 3. Average Order Value per Customer
- the average amount spent per order by each customer.
 */

select customer_id, round(avg(order_value),2) as average_order_value
from orders
group by customer_id
order by average_order_value desc;

/* 
-- 4. Customer Order Status Analysis
-- customer’s orders are distributed by status.
*/

select
customer_id,
sum(order_status = 'Delivered') as delivered_orders,
sum(order_status = 'Cancelled') as cancelled_orders,
sum(order_status = 'Refunded') as refunded_orders
from orders
group by customer_id
order by cancelled_orders desc;

/* 
-- 5. Customer Revenue Contribution
-- What percentage of total revenue comes from each customer.
*/

select
customer_id, sum(order_value) as total_spend,
round(sum(order_value)* 100.0 / sum(sum(order_value)) over (),2) as revenue_contribution_percentage
from orders
group by customer_id
order by revenue_contribution_percentage desc;

/* 
--------------------------------------------------------------------------------
Revenue Analysis
--------------------------------------------------------------------------------
-- Total Revenue
-- Analyse the overall revenue generated by all orders.
 */
 
 select sum(order_value)as total_revenue
 from orders;
 
 /*
Revenue by Customer
Analyse how much revenue each customer generates.
*/

select
customer_id,
sum(order_value) as total_revenue
from orders
group by customer_id
order by total_revenue desc;

 /*
Revenue by Kitchen
Analyse how much revenue each kitchen generates.
 */
 
select kitchen_id, sum(order_value) as total_revenue
from orders
group by kitchen_id
order by total_revenue desc;

/* 
-- Revenue by order Status
-- Analyse revenue across different order statuses
*/

select order_status, sum(order_value) as total_revenue
from orders
group by order_status
order by total_revenue desc;

/*
-- Revenue by Month
-- Analyse how revenue changes month by month.
*/

select
	year(order_date) as order_year,
	month(order_date) as order_month,
	monthname(order_date) as month_name,
	sum(order_value) as total_revenue
from orders
group by
	year(order_date),
	month(order_date),
	monthname(order_date)
order by
	order_year,
	order_month;

/*
--------------------------------------------------------------------------------
Order Analysis
--------------------------------------------------------------------------------
-- Total Orders
-- Measures all Orders Volumes

 */

select count(*) as total_orders
from orders;

/*
-- Orders by status
-- Compare delivered,cancelled and refunded orders.
*/

select order_status, count(*) as total_orders
from orders
group by order_status
order by total_orders desc;

/*
-- Average Order Values
-- Measure average value per order
*/

select round(avg(order_value), 2) as average_order_value
from orders;

/*
-- Orders By Kitchen.
-- Compare order volume across kitchens.
 */
 
select kitchen_id, count(order_id) as total_orders
from orders
group by kitchen_id
order by total_orders desc;

/*
-- Orders by Customer
-- Identify customers with the highest order frequency
 */
 
select customer_id, count(order_id) as total_orders
from orders
group by customer_id
order by total_orders desc;

/*
--------------------------------------------------------------------------------
Kitchen Performance Analysis
--------------------------------------------------------------------------------
-- Total Orders by Kitchen
-- Measure Kitchen Workload
 */

select kitchen_id, count(order_id) as total_orders
from orders
group by kitchen_id
order by total_orders desc;

/*
-- Revenue by Kitchen
-- Measure Kitchen Revenue
 */
 
select kitchen_id, sum(order_value) as total_revenue
from orders
group by kitchen_id
order by total_revenue desc;

/*
-- Average Order Value by Kitchen
-- Compare order value
 */
 
select kitchen_id, round(avg(order_value), 2) as average_order_value
from orders
group by kitchen_id
order by average_order_value desc;

/*
-- Average Delivery Time by Kitchen
-- Compare delivery performance
*/

select kitchen_id, round(avg(delivery_time_min), 2) as average_delivery_time
from orders
group by kitchen_id
order by average_delivery_time;

/*
-- Cancellation Rate by Kitchen
-- Identify cancellation patterns
 */
 
select kitchen_id,
	count(*) as total_orders,
	sum(order_status = 'Cancelled') as cancelled_orders,
	round(sum(order_status = 'Cancelled') * 100.0 / count(*),2) as cancellation_rate
from orders
group by kitchen_id
order by cancellation_rate desc;

/* 
----------------------------------------------------------------------------
Delivery Performace Analysis
----------------------------------------------------------------------------
-- Average Delivery Time
-- Measure Avarage Delivery Time to required orders.
*/

select round(avg(delivery_time_min), 2) as average_delivery_time
from orders;

/*
-- Average Delivery Distance
-- Understand the typical distance covered for each delivery.
*/

select
round(avg(delivery_distance_km), 2) as average_delivery_distance
from orders;

/*
-- Delivery Time by Category
-- Classify deliveries into Fast, Moderate, and Slow based on delivery time.
*/
select
	case
	when delivery_time_min <= 30 then 'Fast'
	when delivery_time_min <= 60 then 'Moderate'
	else 'Slow'
	end as delivery_time_category,
count(*) as total_orders
from orders
group by
	case
	when delivery_time_min <= 30 then 'Fast'
	when delivery_time_min <= 60 then 'Moderate'
	else 'Slow'
end
order by total_orders desc;

/*
-- Average Delivery Time by Distance Category
-- Compare delivery time across Short, Medium, and Long distance categories.

*/

select
case
	when delivery_distance_km <= 5 then 'Short'
	when delivery_distance_km <= 10 then 'Medium'
	else 'Long'
	end as distance_category,
count(*) as total_orders,
round(avg(delivery_time_min), 2) as average_delivery_time
from orders
group by
	case
	when delivery_distance_km <= 5 then 'Short'
	when delivery_distance_km <= 10 then 'Medium'
	else 'Long'
end
order by average_delivery_time;

/*
-- Delivery Cost per Kilometer
-- Measure the average delivery fee relative to distance travelled.
*/

select
round(avg(delivery_fee / delivery_distance_km), 2) as average_delivery_cost_per_km
from orders
where delivery_distance_km > 0;

/*
-- Delivery Efficiency by Kitchen
-- Compare delivery efficiency across kitchens using distance delivered per minute.
*/

select kitchen_id, round(avg(delivery_distance_km / delivery_time_min), 2) as average_delivery_efficiency
from orders
where delivery_time_min > 0
group by kitchen_id
order by average_delivery_efficiency desc;




-- Query 1: Quantity Sold by Category
select category, sum(quantity) as total_quantity_sold
from menu_items
group by category
order by total_quantity_sold desc;


-- Query 2: Revenue by Category
select category, round(sum(quantity * unit_price), 2) as total_sales
from menu_items
group by category
order by total_sales desc;


-- Query 3: Average Unit Price by Category
select category, round(avg(unit_price), 2) as average_unit_price
from menu_items
group by category
order by average_unit_price desc;


-- Query 4: Orders by Category
select category,
count(distinct order_id) as total_orders
from menu_items
group by category
order by total_orders desc;


-- Query 5: Top 10 Menu Items by Sales
select item_id, item_name, category,
	sum(quantity) as total_quantity_sold,
	round(sum(quantity * unit_price), 2) as total_sales
from menu_items
group by
	item_id,
	item_name,
	category
order by total_sales desc
limit 10;




-- Query 1: Customer Count by Segment
select
customer_segment,
count(*) as total_customers
from customers
group by customer_segment
order by total_customers desc;


-- Query 2: Orders by Customer Segment
select
c.customer_segment,
count(o.order_id) as total_orders
from customers c
join orders o
on c.customer_id = o.customer_id
group by c.customer_segment
order by total_orders desc;


-- Query 3: Revenue by Customer Segment
select
c.customer_segment,
round(sum(o.order_value), 2) as total_revenue
from customers c
join orders o
on c.customer_id = o.customer_id
group by c.customer_segment
order by total_revenue desc;


-- Query 4: Average Order Value by Customer Segment
select
c.customer_segment,
round(avg(o.order_value), 2) as average_order_value
from customers c
join orders o
on c.customer_id = o.customer_id
group by c.customer_segment
order by average_order_value desc;


-- Query 5: Average Customer Spending by Segment
select
c.customer_segment,
round(sum(o.order_value) / count(distinct c.customer_id), 2) as average_customer_spend
from customers c
join orders o
on c.customer_id = o.customer_id
group by c.customer_segment
order by average_customer_spend desc;




-- Query 1: Overall Cancellation and Refund Rate
select
count(*) as total_orders,
sum(order_status = 'Cancelled') as cancelled_orders,
sum(order_status = 'Refunded') as refunded_orders,
round(
sum(order_status = 'Cancelled') * 100.0 / count(*),
2
) as cancellation_rate,
round(
sum(order_status = 'Refunded') * 100.0 / count(*),
2
) as refund_rate
from orders;


-- Query 2: Cancellation and Refund by Kitchen
select
kitchen_id,
count(*) as total_orders,
sum(order_status = 'Cancelled') as cancelled_orders,
sum(order_status = 'Refunded') as refunded_orders,
round(
sum(order_status = 'Cancelled') * 100.0 / count(*),
2
) as cancellation_rate,
round(
sum(order_status = 'Refunded') * 100.0 / count(*),
2
) as refund_rate
from orders
group by kitchen_id
order by cancellation_rate desc;


-- Query 3: Cancellation and Refund by Customer Segment
select
c.customer_segment,
count(o.order_id) as total_orders,
sum(o.order_status = 'Cancelled') as cancelled_orders,
sum(o.order_status = 'Refunded') as refunded_orders,
round(
sum(o.order_status = 'Cancelled') * 100.0 / count(o.order_id),
2
) as cancellation_rate,
round(
sum(o.order_status = 'Refunded') * 100.0 / count(o.order_id),
2
) as refund_rate
from customers c
join orders o
on c.customer_id = o.customer_id
group by c.customer_segment
order by cancellation_rate desc;


-- Query 4: Cancellation and Refund by Month
select
year(order_date) as order_year,
month(order_date) as order_month,
monthname(order_date) as month_name,
count(*) as total_orders,
sum(order_status = 'Cancelled') as cancelled_orders,
sum(order_status = 'Refunded') as refunded_orders,
round(
sum(order_status = 'Cancelled') * 100.0 / count(*),
2
) as cancellation_rate,
round(
sum(order_status = 'Refunded') * 100.0 / count(*),
2
) as refund_rate
from orders
group by
year(order_date),
month(order_date),
monthname(order_date)
order by
order_year,
order_month;


-- Query 5: Cancellation and Refund by Delivery Distance Category
select
case
when delivery_distance_km <= 5 then 'Short'
when delivery_distance_km <= 10 then 'Medium'
else 'Long'
end as distance_category,
count(*) as total_orders,
sum(order_status = 'Cancelled') as cancelled_orders,
sum(order_status = 'Refunded') as refunded_orders,
round(
sum(order_status = 'Cancelled') * 100.0 / count(*),
2
) as cancellation_rate,
round(
sum(order_status = 'Refunded') * 100.0 / count(*),
2
) as refund_rate
from orders
group by
case
when delivery_distance_km <= 5 then 'Short'
when delivery_distance_km <= 10 then 'Medium'
else 'Long'
end
order by cancellation_rate desc;



-- Query 1: Orders by Month
select
year(order_date) as order_year,
month(order_date) as order_month,
monthname(order_date) as month_name,
count(*) as total_orders
from orders
group by
year(order_date),
month(order_date),
monthname(order_date)
order by
order_year,
order_month;


-- Query 2: Revenue by Month
select
year(order_date) as order_year,
month(order_date) as order_month,
monthname(order_date) as month_name,
round(sum(order_value), 2) as total_revenue
from orders
group by
year(order_date),
month(order_date),
monthname(order_date)
order by
order_year,
order_month;


-- Query 3: Orders by Day of Week
select
dayofweek(order_date) as day_number,
dayname(order_date) as day_name,
count(*) as total_orders
from orders
group by
dayofweek(order_date),
dayname(order_date)
order by day_number;


-- Query 4: Orders by Hour
select
hour(order_date) as order_hour,
count(*) as total_orders
from orders
group by hour(order_date)
order by order_hour;


-- Query 5: Weekend vs Weekday Performance
select
case
when dayofweek(order_date) in (1, 7) then 'Weekend'
else 'Weekday'
end as day_type,
count(*) as total_orders,
round(sum(order_value), 2) as total_revenue,
round(avg(order_value), 2) as average_order_value
from orders
group by
case
when dayofweek(order_date) in (1, 7) then 'Weekend'
else 'Weekday'
end
order by total_orders desc;